name: Build and push to Github Container Registry

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ "web", "worker", "beat" ]
    steps:
      - uses: actions/checkout@v4
      - name: Prepare tag name
        id: tag_name
        run: echo "repository_lowercase=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.image }}.Dockerfile
          platforms: linux/amd64
          push: true
          cache-to: type=gha,mode=max
          cache-from: type=gha
          tags: |
            ghcr.io/${{ steps.tag_name.outputs.repository_lowercase }}:latest-${{ matrix.image }}
            ghcr.io/${{ steps.tag_name.outputs.repository_lowercase }}:${{ github.sha }}-${{ matrix.image }}